template-file-path: driftdetection.yaml
parameters:
  SnsSubscriptionProtocol: email
  CustomerManagedKey: ''
  PrincipalOrgID: ''
  ManagementAccountId: ''
  MaximumExecutionFrequency: Three_Hours
  SnsSubscriptionEndpoint: yiwill@amazon.com
tags: {}
